# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20161111_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asociacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCargo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=10)),
                ('cargoPersonal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Cargo')),
            ],
        ),
        migrations.AddField(
            model_name='incidencia',
            name='descripcion',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='nombre',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='lista_incidencia',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='lista_incidencia',
            name='nombre',
        ),
        migrations.AlterUniqueTogether(
            name='lista_incidencia',
            unique_together=set([('idEquipo', 'idIncidencia')]),
        ),
        migrations.AddField(
            model_name='asociacion',
            name='idIncidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Incidencia'),
        ),
        migrations.AddField(
            model_name='asociacion',
            name='idPersonal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Personal'),
        ),
        migrations.AlterUniqueTogether(
            name='asociacion',
            unique_together=set([('idIncidencia', 'idPersonal')]),
        ),
    ]
