# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20161117_1859'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asociacion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='asociacion',
            name='idIncidencia',
        ),
        migrations.RemoveField(
            model_name='asociacion',
            name='idPersonal',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='cargoPersonal',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='nombre',
        ),
        migrations.AddField(
            model_name='lista_incidencia',
            name='descripcion',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lista_incidencia',
            name='nombre',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Asociacion',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
