# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20161126_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='nombre',
        ),
        migrations.AddField(
            model_name='lista_incidencia',
            name='descripcion',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lista_incidencia',
            name='nombre',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
