# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20161126_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='descripcion',
            new_name='nombreEquipo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='fechaInstalacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='fechaLlegada',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fechaInicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fechaTermino',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='cantidadEquipos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='tipoUbicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Tipo_Ubicacion'),
        ),
    ]
