# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20161129_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_ubicacion',
            old_name='nombreTipo',
            new_name='nombreTipoUbicacion',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='cantidadEquipos',
        ),
    ]
