# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20161129_2151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lista_incidencia',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='lista_incidencia',
            name='idEquipo',
        ),
        migrations.RemoveField(
            model_name='lista_incidencia',
            name='idIncidencia',
        ),
        migrations.AddField(
            model_name='equipo',
            name='Incidencias',
            field=models.ManyToManyField(blank=True, to='inventario.Incidencia'),
        ),
        migrations.AlterUniqueTogether(
            name='lista_atributo',
            unique_together=set([('idEquipo', 'idAtributo')]),
        ),
        migrations.DeleteModel(
            name='Lista_Incidencia',
        ),
    ]
