# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_auto_20161130_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='Incidencias',
        ),
        migrations.AddField(
            model_name='lista_incidencia',
            name='idEquipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Equipo'),
        ),
        migrations.AddField(
            model_name='lista_incidencia',
            name='idIncidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Incidencia'),
        ),
        migrations.AlterUniqueTogether(
            name='lista_incidencia',
            unique_together=set([('idEquipo', 'idIncidencia')]),
        ),
    ]
